#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Array-Utils
Version  : 0.5
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/Z/ZM/ZMIJ/Array/Array-Utils-0.5.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZM/ZMIJ/Array/Array-Utils-0.5.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liba/libarray-utils-perl/libarray-utils-perl_0.5-1.debian.tar.xz
Summary  : small utils for array manipulation
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Array-Utils-license
Requires: perl-Array-Utils-man

%description
A small pure-perl module containing list manipulation routines.
See the documentation within the module for details on its use.

%package license
Summary: license components for the perl-Array-Utils package.
Group: Default

%description license
license components for the perl-Array-Utils package.


%package man
Summary: man components for the perl-Array-Utils package.
Group: Default

%description man
man components for the perl-Array-Utils package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Array-Utils-0.5
mkdir -p %{_topdir}/BUILD/Array-Utils-0.5/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Array-Utils-0.5/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Array-Utils
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Array-Utils/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Array/Utils.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Array-Utils/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Array::Utils.3
