#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Array-Utils
Version  : 0.5
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/Z/ZM/ZMIJ/Array/Array-Utils-0.5.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZM/ZMIJ/Array/Array-Utils-0.5.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liba/libarray-utils-perl/libarray-utils-perl_0.5-1.debian.tar.xz
Summary  : small utils for array manipulation
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Array-Utils-license = %{version}-%{release}
Requires: perl-Array-Utils-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
A small pure-perl module containing list manipulation routines.
See the documentation within the module for details on its use.

%package dev
Summary: dev components for the perl-Array-Utils package.
Group: Development
Provides: perl-Array-Utils-devel = %{version}-%{release}
Requires: perl-Array-Utils = %{version}-%{release}

%description dev
dev components for the perl-Array-Utils package.


%package license
Summary: license components for the perl-Array-Utils package.
Group: Default

%description license
license components for the perl-Array-Utils package.


%package perl
Summary: perl components for the perl-Array-Utils package.
Group: Default
Requires: perl-Array-Utils = %{version}-%{release}

%description perl
perl components for the perl-Array-Utils package.


%prep
%setup -q -n Array-Utils-0.5
cd %{_builddir}
tar xf %{_sourcedir}/libarray-utils-perl_0.5-1.debian.tar.xz
cd %{_builddir}/Array-Utils-0.5
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Array-Utils-0.5/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Array-Utils
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Array-Utils/6a9386e8ee43075f9a027fdb2f5b1fbd30675779
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Array::Utils.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Array-Utils/6a9386e8ee43075f9a027fdb2f5b1fbd30675779

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Array/Utils.pm
